PROJECT = pigeonhol
OBJ = main.o observer.o
CPP = g++
FLAGS = -Wall -ansi -pedantic-errors

compile:
	$(CPP) -c main.cpp -o main.o $(FLAGS)
	$(CPP) -c observer.cpp -o observer.o $(FLAGS)
	$(CPP) $(OBJ) -o $(PROJECT) $(FLAGS)
